@startuml "UML Project"

skinparam monochrome flase 
skinparam handwritten false 
skinparam shadowing true
skinparam StereotypeABackgroundColor true
skinparam classAttributeIconSize 0

skinparam class{
    
    BackgroundColor bab
    BorderColor Black
    ArrowColor Black
}


class Estudiante {
+ codigoEstudiantil: int 
Verifycode()
}


class Materia {
+ codigoM: int 
+ tipoM: String  
+ semestre: Tsemestre
+ nombreMat : String
+ numeroCred : int
+ mallacurricular: MallaCurricular
}

Class MallaCurricular { 
+ materias : List [Materia]
PrintMalla()
}

Class Semester {

Search()
PrintSemester()
}


Class Electiva { 
+ nombreElect : Nelectiva
+ tipoM: String
}

Class Obligatoria {
+ nombreA: String 
+ tipoM: String
}

Class ActividadesExtra {
+ tipo: Textra 
PrintActivities()
}

Class Rating {
Recommendation()
AddSubject()
}
enum TSemestre {
    Primero
    Segundo 
    Tercero
    Cuarto
    Quinto
    Sexto
    Séptimo
    Octavo 
    Noveno 
    Décimo
}

enum Textra {
    Baile
    Deporte
}

enum Nelectiva {

    Elect. en historia
    Elect. en humanidades 
    Elect. ciencias de la vida
    Elect. en ciencias básicas
    Elect. básica profesional 
    Elect. en ética
    Elect. en ciencias sociales
    Elect. innovación DLLO y SOC
    Elect. profesional I 
    Elect. en redes 
    Elect. en filosofía
    Elect. CS de la computación 
    Elect. gestión informática
    Elect. profesional II
    Elect. estudios del Caribe
    Elect. profesional III

}


Estudiante - MallaCurricular
MallaCurricular " 1   "--- "many" Materia :  < go in 
Materia "  * " <|--- "  1..*  " Obligatoria
Materia "1..*    " <|--- "   *" Electiva
Materia "1..*    " <|--- "   *" Semester
Estudiante "1..*" --* "1  " ActividadesExtra
Materia - Rating



@enduml
